# Generated by Django 5.2.4 on 2025-09-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sizes',
            field=models.JSONField(default=list),
        ),
    ]
